// <auto-generated />
using System;
using System.Collections.Generic;
using Fitness_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fitness_Api.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    [Migration("20260506162219_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            SenderRole = "Trainer",
                            SentAt = new DateTime(2026, 5, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Не забудь про тренировку завтра",
                            TrainerId = 1
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Петров Алексей",
                            Phone = "+7 900 111-22-33"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Иванова Анна",
                            Phone = "+7 901 222-33-44"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров Максим",
                            Phone = "+7 902 333-44-55"
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReminderSent = false,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = "Стандарт"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            EndDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReminderSent = false,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = "Премиум"
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.PersonalPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("NutritionPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<string>("TrainingPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            NutritionPlan = "Белок 1.6 г/кг, вода 2 л в день",
                            ProgressPercent = 35,
                            TrainerId = 1,
                            TrainingPlan = "3 силовые тренировки в неделю"
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.PushNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            SentAt = new DateTime(2026, 5, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Тренировка завтра в 18:00"
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.Role", b =>
                {
                    b.Property<int>("id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_Role"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_Role");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            id_Role = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            id_Role = 2,
                            Name = "Client"
                        },
                        new
                        {
                            id_Role = 3,
                            Name = "Trainer"
                        },
                        new
                        {
                            id_Role = 4,
                            Name = "SalesManager"
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.Session", b =>
                {
                    b.Property<int>("id_Session")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_Session"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("id_Session");

                    b.HasIndex("User_Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Fitness_Api.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Артем Орлов",
                            Specialization = "Силовой тренинг"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Екатерина Белова",
                            Specialization = "Йога"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Иван Смирнов",
                            Specialization = "Функциональные тренировки"
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.User", b =>
                {
                    b.Property<int>("id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_User"));

                    b.Property<int?>("Client_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Trainer_Id")
                        .HasColumnType("integer");

                    b.HasKey("id_User");

                    b.HasIndex("Client_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role_Id");

                    b.HasIndex("Trainer_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id_User = 1,
                            Description = "Администратор клуба",
                            Email = "admin@pulse.local",
                            Name = "Pulse Admin",
                            Password = "588C55F3CE2B8569B153C5ABBF13F9F74308B88A20017CC699B835CC93195D16",
                            Role_Id = 1
                        },
                        new
                        {
                            id_User = 2,
                            Description = "Менеджер по продажам",
                            Email = "sales@pulse.local",
                            Name = "Sales Lead",
                            Password = "588C55F3CE2B8569B153C5ABBF13F9F74308B88A20017CC699B835CC93195D16",
                            Role_Id = 4
                        },
                        new
                        {
                            id_User = 3,
                            Description = "Силовой тренинг",
                            Email = "trainer1@pulse.local",
                            Name = "Артем Орлов",
                            Password = "588C55F3CE2B8569B153C5ABBF13F9F74308B88A20017CC699B835CC93195D16",
                            Role_Id = 3,
                            Trainer_Id = 1
                        },
                        new
                        {
                            id_User = 4,
                            Client_Id = 1,
                            Description = "Клиент фитнес-клуба",
                            Email = "client1@pulse.local",
                            Name = "Петров Алексей",
                            Password = "588C55F3CE2B8569B153C5ABBF13F9F74308B88A20017CC699B835CC93195D16",
                            Role_Id = 2
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessType = "QR",
                            ClientId = 1,
                            EnteredAt = new DateTime(2026, 5, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExitedAt = new DateTime(2026, 5, 6, 13, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<List<int>>("ClientIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 15,
                            ClientIds = new List<int> { 1 },
                            StartAt = new DateTime(2026, 5, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Functional Core",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 12,
                            ClientIds = new List<int>(),
                            StartAt = new DateTime(2026, 5, 8, 19, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Yoga Flow",
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("Fitness_Api.Models.ChatMessage", b =>
                {
                    b.HasOne("Fitness_Api.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Api.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Api.Models.Membership", b =>
                {
                    b.HasOne("Fitness_Api.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Api.Models.PersonalPlan", b =>
                {
                    b.HasOne("Fitness_Api.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Api.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Api.Models.PushNotification", b =>
                {
                    b.HasOne("Fitness_Api.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Api.Models.Session", b =>
                {
                    b.HasOne("Fitness_Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Api.Models.User", b =>
                {
                    b.HasOne("Fitness_Api.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fitness_Api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Api.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("Trainer_Id")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Fitness_Api.Models.Visit", b =>
                {
                    b.HasOne("Fitness_Api.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Api.Models.WorkoutSession", b =>
                {
                    b.HasOne("Fitness_Api.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
